# .github/actions/docker-compose/action.yml
name: 'Docker-Compose Setup'
description: 'Sets up docker-compose'
runs:
  using: 'composite'
  steps:
    - name: Download Docker-Compose plugin
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/bin
        curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o ${{ runner.temp }}/bin/docker-compose
        echo "${{ runner.temp }}/bin" >> $GITHUB_PATH
    - name: Make plugin executable
      shell: bash
      run: chmod +x ${{ runner.temp }}/bin/docker-compose
